# Generated by Django 4.1.4 on 2022-12-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cessao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cessao',
            name='ccb',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cessao',
            name='data_de_emissao',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cessao',
            name='data_de_vencimento',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cessao',
            name='doc_originador',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cessao',
            name='id_cessao',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cessao',
            name='id_externo',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cessao',
            name='parcela',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cessao',
            name='total_parcelas',
            field=models.CharField(max_length=250),
        ),
    ]
