# Generated by Django 4.1.4 on 2022-12-09 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cessao', '0002_alter_cessao_ccb_alter_cessao_data_de_emissao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cessao',
            name='id_externo',
        ),
    ]
